spring.application.name=chat-backend
server.port=8080

# Conexión directa a tu BD 'javachat_db' en Mongo Atlas
spring.data.mongodb.uri=${MONGO_URI}


# Permitir que Spring reconozca las cabeceras Forwarded del proxy de Render
server.forward-headers-strategy=native

# Desactivar el escaneo estricto de TLDs de Tomcat que a veces corrompe handshakes en la nube
server.tomcat.additional-tld-skip-jars=*