spring.application.name=chat-backend
server.port=${PORT:8080}
server.address=0.0.0.0
# Conexión directa a tu BD 'javachat_db' en Mongo Atlas
spring.data.mongodb.uri=${MONGO_URI}

server.http2.enabled=false

server.forward-headers-strategy=framework

server.tomcat.additional-tld-skip-jars=*
server.tomcat.max-http-form-post-size=20MB
server.tomcat.max-parameter-count=1000


